---
title: 'India: Battle With COVID-19'
author: "David Jackson"
date: "`r Sys.time()`"
output:
   html_document:
    fig_width: 9
    fig_height: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,error = FALSE, warning = FALSE)
library(ggplot2)
library(scales)
library(RSQLite)
library(plotly)
library(forecast)
library(timetk)
theme_set(theme_linedraw())
```

## India's Battle with COVID-19 (Rolling 365 Days)

```{r}
rm(list=ls())
source("../DATA/movavg.R")

db <- dbConnect(SQLite(), dbname="../COVID-19-DB/OURWORLD.sqlite3")
df <- dbGetQuery(db,"select * from OWID")
df$date <- as.Date(df$date)
df <- subset(df,location =="India" & date >=Sys.Date() -365 )

sum(df$new_cases,na.rm = TRUE)
sum(df$new_deaths,na.rm=TRUE)

```
```{r}

US <- df[order(df$date,decreasing = TRUE),]
US$MAC <- ma(US$new_cases,7,centre=TRUE)
US$MAD <- ma(US$new_deaths,7,centre=TRUE)
US$Rate <- US$new_deaths/US$new_cases
```

### Cases and Deaths by Year

```{r}
df$Year <- lubridate::year(df$date)
df$Year <- as.factor(df$Year)
ggplot(df) + geom_col(aes(x=Year,y=new_cases)) +
  labs(title = "Covid-19 Cases By Year") +
  scale_y_continuous(labels = comma)

ggplot(df) + geom_col(aes(x=Year,y=new_deaths)) +
  labs(title = "Covid-19 Deaths By Year") +
  scale_y_continuous(labels = comma)
```

### Plot of Daily new_cases and new_deaths

```{r}
daily_new_cases <-ggplot(US) + 
  labs(title="COVID-19 Cases by Date",y="Cases") +
    geom_line(aes(x=date,y=MAC,col="Mov Average")) +
   geom_line(aes(x=date,y=new_cases,col="Daily Cases")) +
  scale_y_continuous(labels = comma)
ggplotly(daily_new_cases)


daily_new_deaths <-ggplot(US) + 
  labs(title="COVID-19 Deaths  by Date",col="Deaths",y="Deaths") + ylim(0,10000) +
  geom_line(aes(x=date,y=MAD,col="Mov. Average")) +
   geom_line(aes(x=date,y=new_deaths,col="Daily Deaths")) +
  scale_y_continuous(labels = comma)
 ggplotly(daily_new_deaths)

```


```{r}
# USA <- subset(US,date >="2020-06-01")
# ggplot(USA) + # geom_line(aes(x=date,y=new_cases,col="Daily new_cases")) +
#   labs(title="COVID-19 Cases by Date since Jun. 1, 2020",
#        subtitle = "(7 day rollingmean)") +
#   geom_line(aes(x=date,y=MAC,col="Rolling Mean")) +
#    scale_alpha_date()
#   
```
```{r}
# ggplot(USA) + # geom_line(aes(x=date,y=new_deaths,col="Daily new_deaths")) +
#   labs(title="COVID-19 Deaths by Date (since Jun. 1, 2020)") + ylim(0,200) +
#   geom_line(aes(x=date,y=MAD,col="Loess")) +
#    scale_alpha_date()
```

#### Non-Moving Average By Week and By Month

```{r}
US$Monthly <- as.Date(cut(US$date,
  breaks = "month"))
US$Weekly <- as.Date(cut(US$date,
  breaks = "week",
  start.on.monday = FALSE))

```
```{r}
Weekly_new_cases <- aggregate(new_cases~Weekly,US,FUN=sum)
Weekly_new_deaths <- aggregate(new_deaths~Weekly,US,FUN=sum)
Weekly_new_cases$DRate <- Weekly_new_deaths$new_deaths/Weekly_new_cases$new_cases
Weekly_new_cases$LivedSaved <- Weekly_new_cases$new_cases * (max(Weekly_new_cases$DRate) - Weekly_new_cases$DRate) 

```
```{r}
ggplot(Weekly_new_cases) + geom_col(aes(x=Weekly,y=new_cases)) + 
  labs(title="Weekly Cases ",x="Date date", y="Weekly new_cases") +
   scale_y_continuous(labels = comma)

ggplot(Weekly_new_deaths) + geom_col(aes(x=Weekly,y=new_deaths)) + 
  labs(title="Weekly Deaths",x="Date date", y="Weekly new_deaths") +
   ylim(0,8000) + 
  scale_y_continuous(labels = comma)
``` 


#### Monthly new_cases and new_deaths



```{r}

Monthly_new_cases <- aggregate(new_cases~Monthly,US,FUN=sum)
Monthly_new_deaths <- aggregate(new_deaths~Monthly,US,FUN=sum)
Monthly_new_cases$DRate <- Monthly_new_deaths$new_deaths/Monthly_new_cases$new_cases
Monthly_new_cases$LivedSaved <- Monthly_new_cases$new_cases * (max(Monthly_new_cases$DRate) - Monthly_new_cases$DRate) * 100
```
```{r}
ggplot(Monthly_new_cases) + geom_col(aes(x=Monthly,y=new_cases)) +
  labs(title="Monthly Cases") +
  scale_y_continuous(labels=scales::comma) +
   scale_y_continuous(labels = comma)

ggplot(Monthly_new_deaths) + geom_col(aes(x=Monthly,y=new_deaths)) +
  labs(title="Monthly Deaths") +
   scale_y_continuous(labels = comma)
```